spring:
  application:
    name: foods
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        default_schema: FOODS

springdoc:
  swagger-ui:
    path=/:

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: DEBUG

eureka:
  client:
    registerWithEureka: true  # Habilita o registro do servi?o no Eureka
    fetchRegistry: true       # Habilita a busca de outros servi?os no Eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL do seu servidor Eureka local

